apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: nginx
spec:
  type: NodePort
  selector:
    app: nginx-demo
  ports:
    - protocol: TCP
      port: 80         # Service port
      targetPort: 80   # Pod port
      nodePort: 30081  # NodePort, pick any port 30000-32767
